baseURL = 'https://dhruvikdonga.github.io/'
languageCode = 'en-us'
title = 'Dhruvik Donga'
theme = 'hugo-coder'
paginate = 10
enableEmoji = true

[markup.highlight]
style = "github-dark"

[params]
  author = "Dhruvik Donga"
  info = "Software Dev"

  description = "Dhruvik's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "images/favicon.svg"
  favicon_32 = "images/favicon-32x32.png"
  favicon_16 = "images/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/DhruvikDonga/"
[[params.social]]
  name = "Linkedin"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/dhruvik-donga-9363a0172/"
[[params.social]]
  name = "Reddit"
  icon = "fa fa-reddit fa-2x"
  weight = 3
  url = "https://www.reddit.com/user/dhruvik_d"
[[params.social]]
  name = "Instagram"
  icon = "fa fa-instagram fa-2x"
  weight = 3
  url = "https://www.instagram.com/dongadhruvik/"
[[params.social]]
  name = "personal website"
  icon = "fa fa-globe fa-2x"
  weight = 4
  url = "https://dhruvikdonga.github.io/"
[[params.social]]
  name = "Email me"
  icon = "fa fa-envelope fa-2x"
  weight = 4
  url = "mailto:dongadhruvik@gmail.com"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"
[[menu.main]]
  name = "Work"
  weight = 1
  url = "work/"
[[menu.main]]
  name = "Venture"
  weight = 1
  url = "venture/"
[[menu.main]]
  name = "Open Source"
  weight = 2
  url  = "projects/"

[markup.goldmark.renderer]
  unsafe = true